[package]
name = "toy-pack-derive"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"

[dev-dependencies]
toy-pack = {path = "../toy-pack"}
toy-pack-mp = {path = "../toy-pack-mp"}

[lib]
proc-macro = true

[[example]]
name = "derive"
path = "examples/src/derive.rs"
