pub const ENV_KEY_TOY_API_STORE_GLOGGING_VIEW_TASK_DETAIL: &'static str =
    "TOY_API_STORE_GLOGGING_VIEW_TASK_DETAIL";

pub const ENV_KEY_TOY_API_STORE_GLOGGING_VIEW_TASK_LIST: &'static str =
    "TOY_API_STORE_GLOGGING_VIEW_TASK_LIST";
