[package]
name = "toy-text-parser"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toy-pack = {path = "../toy-pack", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
