[package]
name = "toy-rocksdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
rocksdb = { version = "0.17.0", features = ["multi-threaded-cf"] }

[dev-dependencies]
tempdir = { version = "0.3.7" }
