[package]
name = "supervisor-d"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
dotenv = "0.15.0"
clap = "3.0.0-beta.2"
thiserror = "1.0"

toy = { path = "../../../pkg/toy", features = ["supervisor", "api-client"] }
toy-rt = { path = "../../../pkg/toy-rt" }
toy-jwt = { path = "../../../shared/toy-jwt" }
toy-api = { path = "../../../pkg/toy-api" }
toy-tracing = { path = "../../../pkg/toy-tracing" }

# plugins
toy-plugin-commons = { path = "../../../plugins/toy-plugin-commons/toy-plugin-commons"}
