[package]
name = "supervisor-d"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
dotenv = "0.15.0"
clap = { version = "3.0.0-rc.7", features = ["derive", "env"] }
thiserror = "1.0"

toy = { path = "../../../pkg/toy", features = ["supervisor", "api-client"] }
toy-rt = { path = "../../../pkg/toy-rt" }
toy-jwt = { path = "../../../shared/toy-jwt" }
toy-api = { path = "../../../pkg/toy-api" }
toy-tracing = { path = "../../../pkg/toy-tracing" }

toy-pack = {path = "../../../shared/toy-pack", features = ["derive"]}
toy-pack-yaml = {path = "../../../shared/toy-pack-yaml"}
toy-pack-json = {path = "../../../shared/toy-pack-json"}

# plugins
toy-plugin-commons = { path = "../../../plugins/toy-plugin-commons/toy-plugin-commons"}
