[package]
name = "console-backend"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# common
log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.2"
dotenv = "0.15.0"
async-trait = "0.1.42"

# core
toy = { path = "../../../pkg/toy" }
toy-rt = { path = "../../../pkg/toy-rt"}

# api
toy-api-server = { path = "../../../pkg/toy-api-server"}
toy-h = { path = "../../../shared/toy-h", features = ["impl_reqwest"]}

# plugins
toy-plugin-commons = { path = "../../../plugins/toy-plugin-commons/toy-plugin-commons"}

# store
toy-api-store-etcd = { path = "../../../pkg/toy-api-store-etcd"}
toy-api-store-glogging = { path = "../../../pkg/toy-api-store-glogging"}

# auth
toy-api-auth-firebase = { path = "../../../pkg/toy-api-auth-firebase"}
