[package]
name = "toy-pack-core-example"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2018"

[[bin]]
name = "hello"
path = "src/hello.rs"

[dependencies]
toy-core = { path = "../toy-core"}
