[package]
name = "toy-config"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
toy-pack = {path = "../toy-pack"}
toy-pack-yaml = {path = "../toy-pack-yaml"}
