name: ci-lib

on:
  push:
    paths:
      - 'pkg/**'
      - 'shared/**'
      - 'plugins/**'

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  test-shared:
    name: build toy shared
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os:
            - windows-latest
            - ubuntu-latest
            - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-07-05
        profile: minimal
        override: true

    - name: test-pkg
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/pkg/Cargo.toml

    - name: test-shared-gauth
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-gauth/Cargo.toml

    - name: test-shared-glogging
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-glogging/Cargo.toml

    - name: test-shared-h
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-h/Cargo.toml

    - name: test-shared-pack
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack/Cargo.toml

    - name: test-shared-pack-mp
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-mp/Cargo.toml

    - name: test-shared-pack-json
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-json/Cargo.toml

    - name: test-shared-pack-urlencoded
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-urlencoded/Cargo.toml

    - name: test-shared-pack-yaml
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-yaml/Cargo.toml

    - name: test-shared-pack-derive
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-derive/Cargo.toml

    - name: test-shared-text-parser
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-text-parser/Cargo.toml

    - name: test-shared-jwt
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-jwt/Cargo.toml

  test-plugin:
    name: build toy plugin
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-05
          profile: minimal
          override: true

      - name: test-plugin-commons
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/plugins/toy-plugin-commons/Cargo.toml

      - name: test-plugin-js
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/plugins/toy-plugin-js/Cargo.toml
        if: !startsWith(matrix.os, 'windows')
