name: ci-lib

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'pkg/**'
      - 'shared/**'
      - 'plugins/**'

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: --cfg tokio_unstable

jobs:
  test-pkg:
    name: build toy pkg
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os:
            - windows-latest
            - ubuntu-latest
            - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - run: rustup update nightly --no-self-update && rustup default nightly

    - name: test-pkg
      run: cargo test --manifest-path ${{ github.workspace }}/pkg/Cargo.toml

  test-shared:
    name: build toy shared
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os:
            - windows-latest
            - ubuntu-latest
            - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - run: rustup update nightly --no-self-update && rustup default nightly

    - name: Remove msys64 # Workaround to resolve link error with C:\msys64\mingw64\bin\libclang.dll
      if: runner.os == 'Windows'
      run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse

    - name: Install dependencies
      if: runner.os == 'Windows'
      run: choco install llvm -y

    - name: test-shared-gauth
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-gauth/Cargo.toml

    - name: test-shared-glogging
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-glogging/Cargo.toml

    - name: test-shared-h
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-h/Cargo.toml

    - name: test-shared-pack
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack/Cargo.toml

    - name: test-shared-pack-mp
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-mp/Cargo.toml

    - name: test-shared-pack-json
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-json/Cargo.toml

    - name: test-shared-pack-urlencoded
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-urlencoded/Cargo.toml

    - name: test-shared-pack-yaml
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-yaml/Cargo.toml

    - name: test-shared-pack-derive
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-derive/Cargo.toml

    - name: test-shared-text-parser
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-text-parser/Cargo.toml

    - name: test-shared-jwt
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-jwt/Cargo.toml

    - name: test-shared-rocksdb
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path ${{ github.workspace }}/shared/toy-rocksdb/Cargo.toml

    - name: test-shared-influxdb
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path ${{ github.workspace }}/shared/toy-influxdb/Cargo.toml

  test-plugin:
    name: build toy plugin
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: rustup update nightly --no-self-update && rustup default nightly

      - name: Remove msys64 # Workaround to resolve link error with C:\msys64\mingw64\bin\libclang.dll
        if: runner.os == 'Windows'
        run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse

      - name: Install dependencies
        if: runner.os == 'Windows'
        run: choco install llvm -y

      - name: test-plugin-commons
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/plugins/toy-plugin-commons/Cargo.toml

      - name: test-plugin-js
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/plugins/toy-plugin-js/Cargo.toml
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')

      - name: test-plugin-lua
        uses: actions-rs/cargo@v1
        with:
            command: test
            args: --manifest-path ${{ github.workspace }}/plugins/toy-plugin-lua/Cargo.toml
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
