name: ci-lib

on:
  push:
    branches:
      - master
    paths:
      - 'pkg/**'
      - 'shared/**'
      - 'plugins/**'

jobs:
  build:
    name: build toy lib
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true

    - name: test-pkg
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/pkg/Cargo.toml

    - name: test-shared-gauth
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-gauth/Cargo.toml

    - name: test-shared-glogging
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-glogging/Cargo.toml

    - name: test-shared-h
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-h/Cargo.toml

    - name: test-shared-pack
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack/Cargo.toml

    - name: test-shared-pack-mp
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-mp/Cargo.toml

    - name: test-shared-pack-json
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-json/Cargo.toml

    - name: test-shared-pack-yaml
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-yaml/Cargo.toml

    - name: test-shared-pack-derive
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/shared/toy-pack-derive/Cargo.toml

    - name: test-shared-text-parser
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --manifest-path ${{ github.workspace }}/shared/toy-text-parser/Cargo.toml

    - name: test-plugin-commons
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ${{ github.workspace }}/plugins/toy-plugin-commons/Cargo.toml
