name: CI

on: [push]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: pkg/toy-core
    
    - name: Install Rust
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
      
