name: CI

on: [push]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: pkg/toy-core
      
    - name: Test
      uses: actions-rs/cargo@v1
      with:
          command: test
      
